name: on-push-terraform

# triger function for merge into master with changes made in terraform folder

on:
  push:
    branches: [ master ]
    paths: [ 'terraform/**' ]
  
name: on-push-terraform

jobs:
  deploy:
    name: apply
    runs-on: ubuntu-20.04

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
# Checkout the repository to the GitHub Actions runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
# Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
        - name: initialise, plan and apply terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}        
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          make all
