name: on-pr-terraform

# triger function for pull request on master and when changes were made in terraform folder

on:
  pull_request:
    branches: [ master ]
    paths: [ 'terraform/**' ]
  
jobs:
  deploy:
    name: plan
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
# Checkout the repository to the GitHub Actions runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
# Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc. 
# Generates an execution plan for Terraform 
      - name: initialise and plan terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          make tf-ci-plan
